### ISSUE TITLE
How to set symbol to line number and initial number

### ISSUE THREAD

**Issue by colin4124** [CodeFalling/nlinum-relative#3]
1) How to set symbol to line number, not the characters, such as  '->' .

2) The initial relative line number is 1, so if I want to copy or delete lines relative to current line, I have to do this `y/d (relative line + 1)` . So, how to set the relative line number to 2?

**Comment by xcodebuild** [comment]
1. Just `(setq nlinum-relative-current-symbol "")`
2. Maybe something like `offset` would be good. I'll add it

**Comment by colin4124** [comment]
thinks very much.

**Comment by xcodebuild** [comment]
`(setq nlinum-relative-offset 1)` is here now @colin4124

**Comment by colin4124** [comment]
@CodeFalling `(setq nlinum-relative-offset 1)`  . It would make the absolute address + 1. If current is 1, the line number it display is 2.

I have a suggestion, display absolute line number in insert state, relative line number in normal state.
https://www.zhihu.com/question/29892522/answer/46182137

**Comment by xcodebuild** [comment]
@colin4124 oops, my mistake, I'll fix this. 

> display absolute line number in insert state, relative line number in normal state

In fact `(nlinum-relative-setup-evil)` is what you want.

**Comment by xcodebuild** [comment]
@colin4124 163801c8570932106330c6b3d3bc4bfdd23f7bba should fix this bug. But MELPA may take some time to update.

**Comment by colin4124** [comment]
@CodeFalling I have used `(nlinum-relative-setup-evil)` before. I use hybrid editing style not vim, so it has no effect. But I change to vim editing style, normal state is relative line number, and I change to insert state, it disappear. I change back to normal, it can't display  relative line number.

**Comment by xcodebuild** [comment]
@colin4124 de688db04a9bc2a0e3803dfeb34d3dc0a42eaf5d fix this. 😂

**Comment by colin4124** [comment]
@CodeFalling I use it before you put it on MELPA, so I still use from github directly. It works! Think again ^_^

**Comment by colin4124** [comment]
@CodeFalling I found another problem again  :joy: 

When I split two windows, I move in one, and the other one's line number will change.

**Comment by xcodebuild** [comment]
Two windows but one buffer? Because I use a buffer-local var to save line number. Maybe I can try to stop refresh with unfocus window.

**Comment by colin4124** [comment]
@CodeFalling Yes, two windows but one buffer.

**Comment by xcodebuild** [comment]
@colin4124 Seems impossible to "fix" because fontify's object is not `window` but `buffer`. You would find other `fontify` behavior at same time.(such as brackets highlight etc)

**Comment by colin4124** [comment]
@CodeFalling Ok, I got it, thx ^_^
