### ISSUE TITLE
Why is nlinum.el included in here too?

### ISSUE THREAD

**Issue by kaushalmodi** [CodeFalling/nlinum-relative#4]
The original nlinum.el is on GNU Elpa. And you already have the `nlinum` package as a part of Package Requires:

```
;; Package-Requires: ((emacs "24.4") (nlinum "1.5"))
```

So if a user doesn't have `nlinum` installed, it will be installed automatically by the package manager; you do not need to include the same here.

**Comment by wasamasa** [comment]
I'm sort of surprised this has been overlooked in the review for MELPA admission.

**Comment by xcodebuild** [comment]
Sorry I just add this file **after** their review, because I always get a file not found **error** when install it with quelpa.
 Maybe I should remove this file and just ignore the error?

**Comment by xcodebuild** [comment]
However **without `nlinum.el` MELPA just not build this package at all**. I update commit at 9 hours ago. MELPA's build last ended an hour ago and took 6 hours. But version is still `20160513.625` .

MELPA also didn't build this package at previous commit without `nlinum.el`. It's anything I missing? @kaushalmodi @wasamasa

**Comment by wasamasa** [comment]
You should ideally ask that in the same pull request you've opened.

**Comment by purcell** [comment]
No sure, sorry. I'm sure it would have built eventually. I've cleared out the package containing `nlinum.el` manually on the MELPA server and rebuilt it - there's a separate issue in that if you remove files, it might not always update the resulting package version.

**Comment by xcodebuild** [comment]
@purcell So what should I do to fix this? Should I add `linum.el` again?

**Comment by purcell** [comment]
No, just leave it as it is. It's [built on MELPA](https://melpa.org/#/nlinum-relative) now with the correct contents.

**Comment by xcodebuild** [comment]
Thx.
