### ISSUE TITLE
Not work in Terminal

### ISSUE THREAD

**Issue by colin4124** [CodeFalling/nlinum-relative#5]
![deepinscreenshot20160516151203](https://cloud.githubusercontent.com/assets/1255176/15282849/a118de96-1b78-11e6-8a6e-260e88b8e011.png)

The gray line is the current line, it is in normal state. When I move cursor, the top line number is change.

**Comment by colin4124** [comment]
I don't know why, it works now. :joy:

**Comment by xcodebuild** [comment]
I tried in `/Applications/Emacs.app/Contents/MacOS/Emacs -Q -nw`,

``` lisp
(package-initialize)
(require 'evil)
(require 'nlinum-relative)
(nlinum-relative-setup-evil)
(nlinum-relative-on)
```

Everything works well, could you provide steps to reproduce this problem?

**Comment by colin4124** [comment]
I just emacs -nw, haven't -Q . It works now, but it really doesn't works before as screenshot show that.
I can't   reproduce this problem any more.  :joy:
