### ISSUE TITLE
nlinum-relative--timer is void

### ISSUE THREAD

**Issue by colin4124** [CodeFalling/nlinum-relative#7]
`Error in dotspacemacs/user-config: Symbol’s function definition is void: nlinum-relative--timer`

Here is my setting in `dotspacemacs/user-config ()`

>  (nlinum-relative-setup-evil)
>   (add-hook 'prog-mode-hook 'nlinum-relative-mode)
>   (setq nlinum-relative-redisplay-delay 0) 
>   (setq nlinum-relative-current-symbol "")
>   (setq nlinum-relative-offset 1)

**Comment by aaronbieber** [comment]
+1, I am also receiving this error:

`Symbol's function definition is void: nlinum-relative--timer`

I am not using Spacemacs, I am running Emacs 25.1.50.1 (x86_64-apple-darwin15.2.0), and I've pasted in the `use-package` declaration exactly as shown in the README.

Oddly I did not receive this error on my home computer, which is running a slightly older version of Emacs (24.x, I believe).

**Comment by aaronbieber** [comment]
It looks like a typo, shouldn't this line be a `defvar`?

`( nlinum-relative--timer nil)`

https://github.com/CodeFalling/nlinum-relative/blob/master/nlinum-relative.el#L105

**Comment by xcodebuild** [comment]
😳 So sorry, fixed now. But it may take some time to get update on MELPA.

**Comment by aaronbieber** [comment]
Thanks for the quick reply! I fixed it in my local copy so I'll just let MELPA overwrite it the next time I upgrade.
